sudo: false
jdk:
    - oraclejdk8
language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools
    - build-tools-29.0.2
    - android-29
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

script: ./gradlew clean check assembleDebug
